### ISSUE TITLE
Remove default depth

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-git#15]
There should be no default depth. See https://github.com/drone-plugins/drone-git/pull/14

**Comment by sbehrends** [comment]
+1

**Comment by gregory90** [comment]
+1
Gitlab isn't working at the time being because of this:
```
$ git fetch --no-tags --depth=50 origin +refs/heads/master:
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
[info] build failed (exit code 1)
```

Everything is ok, when there's no --depth argument.
