### ISSUE TITLE
Add Nsswitch and custom hosts file to container build

### ISSUE THREAD

**Issue by michaelgibson** [drone-plugins/drone-git#17]
Similar to issue: https://github.com/drone/drone/issues/1269
and PR: https://github.com/drone/drone/pull/1306

Where container is not respecting the local hosts file for lookups.
In my case there is not always DNS available or the DNS is incorrect.
Need a way to manually set that.
Adding an /etc/nsswitch.conf and a custom hosts file seems to resolve this.

ADD contrib/docker/etc/nsswitch.conf
ADD contrib/docker/etc/hosts

**Comment by bradrydzewski** [comment]
@michaelgibson does adding the following line to the Dockerfile resolve?

```
RUN echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf
```

**Comment by michaelgibson** [comment]
That seems to work, at least for the nsswitch part.
Still need to figure out how to get the drone-git container to use a host file or host entries.

May need to look into being able to add network parameters to the drone-git's run 
https://docs.docker.com/engine/reference/run/#managing-etc-hosts
But that is probably another feature request. 

Thanks!

**Comment by tboerger** [comment]
But in that case this must be an alpine issue as the git plugin is based on alpine 3.2

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
