### ISSUE TITLE
Better error reporting on pull requests

### ISSUE THREAD

**Issue by donny-dont** [drone-plugins/drone-git#20]
One of our developers encountered this error.

```
[info] Pulling image plugins/drone-git:latest
Drone Git Plugin built at 2016-02-02 08:48:17 UTC
Drone Git Plugin built at 2016-02-02 08:48:17 UTC
$ git init
Initialized empty Git repository in /drone/src/xxxx/xxxx/xxxx/.git/
$ git remote add origin git@xxxx:xxxx/xxxx.git
$ git fetch --no-tags --depth=50 origin +refs/pull/1985/merge:
Warning: Permanently added 'xxxx' (ECDSA) to the list of known hosts.\r
fatal: Couldn't find remote ref refs/pull/1985/merge
[info] build failed (exit code 1)
```

After talking with @bradrydzewski he mentioned that if the pull request could not be automatically merged then the ref wouldn't be present. Maybe a better error message would be.

```
[error] The ref for the pull request was not found. This is usually due to the branch being merged having conflicts with the target branch.
```

**Comment by SebastianStehle** [comment]
I get this message even when Github tells me that  the PR has no conflicts. Can you explain me why?

**Comment by bradrydzewski** [comment]
You might experience this error if github has not yet created the merge ref. GitHub creates the merge ref asynchronously, which means it can trigger a build before the actual commit is ready to be cloned.

The latest version of the git clone image has [retry logic](https://github.com/drone-plugins/drone-git/commit/dd60daec4ed64250367658c9ee0d35ff73fd2ae5) to work around this GitHub limitation. If you have an old version of the git clone plugin, you can delete, which will force drone to pull the latest version

If you think you are experiencing another issue, I recommend contacting GitHub and inquiring why cloning the ref is failing. At the end of the day, this plugin executes a git clone, and if the clone fails you will need to debug at the remote (GitHub) level.

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
