### ISSUE TITLE
Preserve original branch the commit checked out is from

### ISSUE THREAD

**Issue by bitemyapp** [drone-plugins/drone-git#26]
Branch in build environment is always "master", even if that wasn't the branch that triggered the build. Scripts that case behavior based on branch or otherwise introspect the git repository state are broken by this behavior.

**Comment by Franklin89** [comment]
I just ran into this issue my self. I also have a appveyor instance running and checked how they checkout to preserve the branch. They clone the repo and then checkout the sha. Would this be a possible solution to change the command structure to cloning as well or might this lead to any issues?

master branch
```
git clone -q --branch=master [GIT REPO] [DESTINATION]
git checkout -qf [COMMIT SHA]
```

pull request
```
git clone -q [GIT REPO] [DESTINATION]
git fetch -q origin +refs/pull/8/merge:
git checkout -qf FETCH_HEAD
```

**Comment by rubendura** [comment]
I've just been bitten by this: I tried using `HEAD` in my scripts but it only worked for pushes to `master`. The solution (in my specific case) is to use `${DRONE_COMMIT_SHA}` instead, but it's annoying to find this out when building a feature.

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
