### ISSUE TITLE
Support for sparse checkout

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-git#37]
moved from drone/drone#1849

---

Thanks for providing such an awesome service/project! I really love your simple UI design!

As the main maintainer of a super huge/fat project - @cdnjs, I'm wondering if you would like to support git sparseCheckout. By default, git will checkout all the files from the repository to the filesystem, by sparseCheckout, we can decide to checkout partial of the files, so this will help decrease the number of files git will checkout, which will totally save both disk sapce, cpu time, build time!

There is only a small different steps between git clone and git, but would help a lot for a huge repo :smile: 

Reference:
- https://git-scm.com/docs/git-read-tree
- https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

**Comment by bradrydzewski** [comment]
based on an initial conversation it sounds like this might add a good bit of complexity to the plugin. For this reason I've suggested perhaps it could make sense to create a separate git sparse plugin, instead of putting all the long in one super plugin

```
pipeline:
  clone:
    image: foo/git-sparse-checkout
```

**Comment by PeterDaveHello** [comment]
@bradrydzewski is there any doc about plugin development? Thanks.

**Comment by bradrydzewski** [comment]
closing in favor of the plugin https://github.com/peterdavehello/drone-git-sparse-checkout/
