### ISSUE TITLE
[Documentation] DOCS.md update: "submodule_update_remote" should be "submodules_update_remote"

### ISSUE THREAD

**Issue by johncolarusso** [drone-plugins/drone-git#39]
DOCS.md references the plugin parameter `submodule_update_remote` when it should really be `submodules_update_remote`.
* https://github.com/drone-plugins/drone-git/blob/master/DOCS.md#parameter-reference

As a result, this documentation is incorrect: http://plugins.drone.io/drone-plugins/drone-git/

**Comment by bradrydzewski** [comment]
good catch! I updated to the code to accept `submodule_update_remote` while maintaining backward compatibility with the prior value

**Comment by johncolarusso** [comment]
@bradrydzewski Thanks for the fix!
