### ISSUE TITLE
Support url.insteadOf configuration

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-git#53]
instead of submodule override we might be able to set a global configuration to remap the git+ssh url to git+https url

```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```

**Comment by gamagori** [comment]
@bradrydzewski I'd like to take this on - it would significantly clean up one of my projects. Do you think it's do-able for a Go beginner?

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
