### ISSUE TITLE
support git config options

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-git#54]
support custom git config options

```
git config --add core.gitproxy '"proxy-command" 
```

as a yaml slice parameter:

```
git_config:
  - core.gitproxy proxy-command
  - user.email john@doe.org
```

**Comment by typeless** [comment]
Also `http.PostBuffer` for https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
