### ISSUE TITLE
HOW TO SETTING PERSONAL GITLAB HOSTS?

### ISSUE THREAD

**Issue by icesai** [drone-plugins/drone-git#64]
I create my own gitlab.
My drone-server can find my gitlab.
I got a fail when git clone my repo.
The error is it cat't find my gitlab domain.
I can't setting my hosts in this image.
Is it can be setting?

**Comment by tboerger** [comment]
The clone url gets provided by the drone server. It's up to you to take care that the Gitlab domain can be resolved by the containers. The plugins are using standard docker networking.

**Comment by lixwlixw** [comment]
I have the same problem.
plugins/git:latest  this image running ，then：  fatal: unable to access 'https://github.com/xxxxx/xxxxx.git/': Could not resolve host: github.com
other image running  ,curl  github.com  is a success. 。On the same docker server.
you see see , can this problem be solved?

**Comment by bradrydzewski** [comment]
This indicates there is an issue with your host machine docker configuration. Please read my response to this thread https://discourse.drone.io/t/couldnt-resolve-host-on-clone/281/22
