### ISSUE TITLE
Support cloning as custom user

### ISSUE THREAD

**Issue by vbrandl** [drone-plugins/drone-git#72]
It would be great to be able to clone a repository as another user than `root`. I compile Rust projects using drone and the [ekidd/rust-musl-builder](https://hub.docker.com/r/ekidd/rust-musl-builder/) image. That image runs the build process as the user `rust`. Since the repository is cloned as `root`, the build user has no write permissions, it cannot build the project without explicitly `chown`ing first. I think it would be better to have a user or UID configurable per pipeline that will be used for cloning.

**Comment by bradrydzewski** [comment]
thanks, we already have an open issue for this and are tracking the change :)  Subscribe to https://github.com/drone-plugins/drone-git/pull/71 for updates
