### ISSUE TITLE
New release with updated curl?

### ISSUE THREAD

**Issue by Dirbaio** [drone-plugins/drone-git#75]
I've been running into problems with too long passwords in netrc due to a curl issue. It's been fixed in curl/curl#2676 and released in curl 7.61.0, which is already on the alpine repos.

Could we get a release of the `plugins/git` image with the updated curl? 

Thank you!

**Comment by tboerger** [comment]
We are using a fixed alpine release, we need to check if a curl upgrade have been backported.

**Comment by Dirbaio** [comment]
AFAICT you're using `alpine:3.7` from `plugins/base`, which does get curl 7.61

```
dirbaio@saturn:~$ docker run -ti --rm alpine:3.7
/ # apk add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20171114-r0)
(2/4) Installing libssh2 (1.8.0-r2)
(3/4) Installing libcurl (7.61.0-r0)
(4/4) Installing curl (7.61.0-r0)   <===================  yes!
Executing busybox-1.27.2-r11.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 6 MiB in 17 packages
/ # 
```

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
