### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address exit status 128

### ISSUE THREAD

**Issue by anthosz** [drone-plugins/drone-git#77]
Hello,

Since this morning, we receive this error when we use the plugin:
> fatal: could not read Username for 'https://github.com': No such device or address exit status 128

Probably due to upgrade of this friday?

Best regards,

**Comment by bradrydzewski** [comment]
there was a github outage during this time period that impacted tokens, which is likely the result of this issue.
