### ISSUE TITLE
Can't clone on deployment events ($DRONE_BUILD_EVENT == deployment)

### ISSUE THREAD

**Issue by fsouza** [drone-plugins/drone-git#81]
This is technically GitHub's fault, but I believe we can have a workaround:
when we trigger a GitHub deployment using a tag ref, the webhook payload
doesn't state that the deployment has been created from a tag, and Drone treats
it as a branch (and GitHub makes it even worse when there's a tag and a branch
with the same name, see below).

## How to reproduce

Create a GitHub deployment using a tag ref, wait for GitHub to notify Drone and
see the clone step failing.

Using ``plugins/git:next``:

```
nitialized empty Git repository in /drone/src/github.com/nytm/drone-gh-deploy-exp/.git/
+ git fetch origin +refs/heads/v0.0.2:
fatal: Couldn't find remote ref refs/heads/v0.0.2
```

Using ``plugins/git:latest``:

```
+ git init
Initialized empty Git repository in /drone/src/github.com/nytm/drone-gh-deploy-exp/.git/
+ git remote add origin https://github.com/nytm/drone-gh-deploy-exp.git
+ git fetch --no-tags origin +refs/heads/v0.0.9:
fatal: Couldn't find remote ref refs/heads/v0.0.9
retry in 5s
+ git fetch --no-tags origin +refs/heads/v0.0.9:
fatal: Couldn't find remote ref refs/heads/v0.0.9
retry in 5s
+ git fetch --no-tags origin +refs/heads/v0.0.9:
fatal: Couldn't find remote ref refs/heads/v0.0.9
retry in 5s
+ git fetch --no-tags origin +refs/heads/v0.0.9:
fatal: Couldn't find remote ref refs/heads/v0.0.9
retry in 5s
+ git fetch --no-tags origin +refs/heads/v0.0.9:
fatal: Couldn't find remote ref refs/heads/v0.0.9
retry in 5s
+ git fetch --no-tags origin +refs/heads/v0.0.9:
fatal: Couldn't find remote ref refs/heads/v0.0.9
time="2019-02-05T16:05:45Z" level=fatal msg="exit status 128"
```

(Notice how the plugin is looking for ``refs/heads/v0.0.9`` when it should be
looking for ``refs/tags/v0.0.9``).

## The bug

Technically, there are 2 cases where the plugin misbehaves:

1. the one described above: deploy from a tag, plugins looks for a branch,
   can't find it, build fails
1. when there's actually a branch with the tag name, the plugin silently
   fetches the branch and deploy that instead of the tag.

One workaround we've been using is to fetch both ``refs/heads/`` and
``refs/tags/`` then checking out ``$DRONE_COMMIT``. **BUT** ``$DRONE_COMMIT`` is
actually incorrect for the second case, because GitHub sends the wrong commit
SHA to Drone! (may be related to
[github-ref-bug](https://github.com/fsouza/github-ref-bug)). So, in that case,
we have an extra step that actually fetches the tag and use it when the
deployment was triggered from a tag event (in our case, ``environment: production``):

```yaml
clone:
  git:
    image: fsouza/drone-git
    pull: true

pipeline:
  checkout-tag-production-deployment:
    image: something-with-git
    commands:
      - git fetch origin +refs/tags/${DRONE_BRANCH}:
      - git checkout FETCH_HEAD -b production-branch
    when:
      event: deployment
      environment: production
```

(If you want to see what fsouza/drone-git is doing:
https://github.com/drone-plugins/drone-git/compare/drone-plugins:next...fsouza:fix-tag-deployment)

That solution can't be generalized though, so I wonder what should be the
actual solution for that case. Some ideas:

- **Solution 1:** on deployment events, fetch both ``refs/heads/$DRONE_BRANCH``
  and ``refs/tags/$DRONE_BRANCH`` and if both succeed, fail with an error
  message saying that having branches and tags with the same name isn't
  supported.
- **Solution 2:** on deployment events, fetch both
  ``refs/heads/${DRONE_BRANCH}`` and ``refs/tags/${DRONE_BRANCH}``, checkout
  the wrong ``$GIT_COMMIT`` and print a warning or something like that? (I bet
  users would ignore the warning, or not even see it, so this is dangerous).
- **Solution 3:** leave it alone. Wait for GitHub to fix the issue and have users use a fork of
  drone-git (what we're currently doing). Once GitHub fixes the issue, Solution
  2 would be the way to go because then we'd be checking out the correct
  ``${DRONE_COMMIT}``.
- Something else?

**Comment by bradrydzewski** [comment]
for drone 1.0 we are using a new version of this plugin, which may begin to address this scenario:
https://github.com/drone/drone-git/blob/master/posix/clone#L53:L56

**Comment by fsouza** [comment]
@bradrydzewski isn't that what ``plugins/git:next`` is? We're using that too and we needed this change: https://github.com/drone-plugins/drone-git/compare/drone-plugins:next...fsouza:fix-tag-deployment

**Comment by bradrydzewski** [comment]
yes, `plugins/git:next` was moved to `drone/git` and has since evolved a little bit.  The reason for changing the repository is that the git plugin is very much core to how drone works -- it is the only plugin that is used by very installation out-of-the box -- and therefore needs to be more closely tied to the drone core codebase and organization.

**Comment by fsouza** [comment]
Sorry, couldn't test with Drone 1.0. It looks like GitHub deployments aren't triggering any events in Drone 1.0? Is that integration gone?

Found this link: https://discourse.drone.io/t/drone-1-0-0-rc5-deployment-builds/3580

**Comment by tboerger** [comment]
Replaced by drone/drone-git repository, closing this issue.
